version: '3'
services:
  gortr:
    image: cloudflare/gortr
    command:
      - -ssh.bind
      - :8283
      - -ssh.method.key=true
      - -ssh.auth.key.bypass=true
    networks:
      vpcbr:
        ipv4_address: 10.1.0.4
  bird1:
    build: bird
    entrypoint: bird
    command:
      - -s
      - /bird.sock 
      - -c
      - /etc/bird/bird1.conf
      - -f
      - -d
    volumes:
      - ./bird/config_local/:/etc/bird/
      - ./bird/ssh/id_rsa:/id_rsa
      - ./bird/ssh/id_rsa.pub:/id_rsa.pub
    depends_on:
      - gortr
    networks:
      vpcbr:
        ipv4_address: 10.1.0.2
  bird2:
    build: bird
    entrypoint: bird
    command:
      - -s
      - /bird.sock 
      - -c
      - /etc/bird/bird2.conf
      - -f
      - -d
    volumes:
      - ./bird/config_local/:/etc/bird/
    depends_on:
      - gortr
    networks:
      vpcbr:
        ipv4_address: 10.1.0.3
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.0.0/16
